import { createReducer, createActions } from 'reduxsauce'
import Immutable from 'seamless-immutable'

/* ------------- Types and Action Creators ------------- */

const { Types, Creators } = createActions({
    addSugarLevel: ['sugarLevel'],
    addCalculatedInsuline: ['calculatedInsuline']
})

export const ValuesTypes = Types
export default Creators

/* ------------- Initial State ------------- */

export const INITIAL_STATE = Immutable({
  // types { 1: measure,  2: exercise, 3: meal, 4: measure+meal == calculated }
   events: [
      { type: 1, sugarLevel: 96, date: "November 9th, 2017 7:10 AM" },
      { type: 3, meal_id: 1, carbohydrates: 132, date: "November 9th, 2017 08:22 AM" },
      { type: 1, sugarLevel: 62, date: "November 9th, 2017 1:42 PM" },
      { type: 2, intensity: 3, duration: 120, date: "November 9th, 2017 4:20 PM" },
      { type: 1, sugarLevel: 122, date: "November 9th, 2017 6:31 PM" },
      { type: 1, sugarLevel: 85, date: "November 10th, 2017 7:24 AM" },
      { type: 3, meal_id: 2, carbohydrates: 87, date: "November 10th, 2017 11:15 AM" },
      { type: 1, sugarLevel: 162, date: "November 10th, 2017 12:21 PM" },
      { type: 1, sugarLevel: 124, date: "November 10th, 2017 3:15 PM" },
      { type: 3, meal_id: 3, carbohydrates: 92, date: "November 10th, 2017 5:38 PM" },
      { type: 1, sugarLevel: 145, date: "November 10th, 2017 7:10 PM" },
      { type: 1, sugarLevel: 169, date: "November 10th, 2017 9:32 PM" },
      { type: 1, sugarLevel: 122, date: "November 11th, 2017 8:27 AM" },
      { type: 2, intensity: 2, duration: 120, date: "November 11th, 2017 9:10 AM" },
      { type: 1, sugarLevel: 78, date: "November 11th, 2017 11:02 AM" },
    ],
    static: {
      highSugarLevel: 150,
      lowSugarLevel: 70
    },
    calculatedInsuline: 0,
    food: [
      { nombre: "Cuajada",
        categoria: "Lacteos",
        medida_racion: 200,
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: 0.8,
        indice: 35
      },
      { nombre: "", nombre: "Flan",
        categoria: "Lacteos",
        medida_racion: "50",
        consumo_habitual: "Unidad (125g)",
        raciones_hc: "2.5",
        indice: null
      },
      { nombre: "Heladodecrema",
        categoria: "Lacteos",
        medida_racion: "50",
        consumo_habitual: "Tarrina individual (150ml)",
        raciones_hc: "3",
        indice: 60
      },
      { nombre: "Heladodehielo",
        categoria: "Lacteos",
        medida_racion: "50",
        consumo_habitual: "Unidad (100ml)",
        raciones_hc: "2",
        indice: 65
      },
      { nombre: "Helado_sin_azucar",
        categoria: "Lacteos",
        medida_racion: "100",
        consumo_habitual: "Unidad (100ml)",
        raciones_hc: "1",
        indice: 35
      },
      { nombre: "Kefir",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: "0.5",
        indice: 35
      },
      { nombre: "Leche_desnatada",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Vaso o taza (200ml)",
        raciones_hc: "1",
        indice: 32
      },
      { nombre: "Leche_semidesnatada",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Vaso o taza (200ml)",
        raciones_hc: "1",
        indice: 30
      },
      { nombre: "Leche_entera",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Vaso o taza (200ml)",
        raciones_hc: "1",
        indice: 27
      },
      { nombre: "Leche_condensada",
        categoria: "Lacteos",
        medida_racion: "20",
        consumo_habitual: "Cucharada sopera (20g)",
        raciones_hc: "1",
        indice: 61
      },
      { nombre: "Leche_polvo",
        categoria: "Lacteos",
        medida_racion: "25",
        consumo_habitual: "Cucharada sopera colmada (25g)",
        raciones_hc: "1",
        indice: 30
      },
      { nombre: "Nata_liquida",
        categoria: "Lacteos",
        medida_racion: "300",
        consumo_habitual: "Botell�n o brick (200ml)",
        raciones_hc: "0.7",
        indice: null
      },
      { nombre: "Petit_suisse",
        categoria: "Lacteos",
        medida_racion: "70",
        consumo_habitual: "Unidad (55g)",
        raciones_hc: "0.8",
        indice: 40
      },
      { nombre: "Natillas",
        categoria: "Lacteos",
        medida_racion: "50",
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: "2.5",
        indice: null
      },
      { nombre: "Queso_fresco",
        categoria: "Lacteos",
        medida_racion: "250",
        consumo_habitual: "Tarrina individual (70g)",
        raciones_hc: "0.3",
        indice: 35
      },
      { nombre: "Queso_pasta",
        categoria: "Lacteos",
        medida_racion: "No\nvalorable",
        consumo_habitual: "",
        raciones_hc: "",
        indice: null
      },
      { nombre: "Yogur_natural",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: "0.5",
        indice: 35
      },
      { nombre: "Yogur_desnatado",
        categoria: "Lacteos",
        medida_racion: "125",
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: "1",
        indice: 35
      },
      { nombre: "Yogur_entero",
        categoria: "Lacteos",
        medida_racion: "70",
        consumo_habitual: "Unidad (125ml)",
        raciones_hc: "1.5",
        indice: 35
      },
      { nombre: "Yogur_liquido",
        categoria: "Lacteos",
        medida_racion: "70",
        consumo_habitual: "Unidad (200ml)",
        raciones_hc: "3",
        indice: 40
      },
      {
        nombre: "Yogur_Actimel",
        categoria: "Lacteos",
        medida_racion: "100",
        consumo_habitual: "Unidad (94ml)",
        raciones_hc: "1",
        indice: 35
      },
      { nombre: "Yogur_bajograsa",
        categoria: "Lacteos",
        medida_racion: "200",
        consumo_habitual: "Unidad (94ml)",
        raciones_hc: "0.5",
        indice: 35
      },
      { nombre: "Arroz_cocido",
        categoria: "cereales",
        medida_racion: 38,
        consumo_habitual: "Plato grande (230g)",
        raciones_hc: 6,
        indice: 70
      },
      { nombre: "Arroz_cocido",
        categoria: "cereales",
        medida_racion: 38,
        consumo_habitual: "Plato mediano (150g)",
        raciones_hc: 4,
        indice: 70
      },
      { nombre: "Arroz_cocido",
        categoria: "cereales",
        medida_racion: 38,
        consumo_habitual: "Guarnici�n (75g)",
        raciones_hc: 2,
        indice: 70
      },
      { nombre: "Arroz_integral_cocido",
        categoria: "cereales",
        medida_racion: 40,
        consumo_habitual: "Plato grande (230g)",
        raciones_hc: 6,
        indice: 50
      },
      { nombre: "Arroz_integral_cocido",
        categoria: "cereales",
        medida_racion: 40,
        consumo_habitual: "Plato mediano (150g)",
        raciones_hc: 4,
        indice: 50
      },
      { nombre: "Arroz_integral_cocido",
        categoria: "cereales",
        medida_racion: 40,
        consumo_habitual: "Guarnici�n (75g)",
        raciones_hc: 2,
        indice: 50
      },
      { nombre: "Arroz_hinchado_desayuno",
        categoria: "cereales",
        medida_racion: 12,
        consumo_habitual: "Plato mediano (150g)",
        raciones_hc: 6,
        indice: 85
      },
      { nombre: "Arroz_salvaje_cocido",
        categoria: "cereales",
        medida_racion: 34,
        consumo_habitual: "Plato mediano (120g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Avena_cocido",
        categoria: "cereales",
        medida_racion: 34,
        consumo_habitual: "Plato mediano (120g)",
        raciones_hc: 4,
        indice: 40
      },
      { nombre: "Boniato",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Peque�o\n(80g)",
        raciones_hc: 1.6,
        indice: 50
      },
      { nombre: "Boniato",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Mediano (160g)",
        raciones_hc: 3.2,
        indice: 50
      },
      { nombre: "Boniato",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Grande (320g)",
        raciones_hc: 6.4,
        indice: 50
      },
      { nombre: "Cebada_cocido",
        categoria: "cereales",
        medida_racion: 42,
        consumo_habitual: "Plato mediano (120g)",
        raciones_hc: 4,
        indice: 45
      },
      { nombre: "Centeno_cocido",
        categoria: "cereales",
        medida_racion: 38,
        consumo_habitual: "Mediano (160g)",
        raciones_hc: 3,
        indice: 45
      },
      { nombre: "Cereales_desayuno",
        categoria: "cereales",
        medida_racion: 15,
        consumo_habitual: "Mediano (160g)",
        raciones_hc: 5,
        indice: 77
      },
      {
        nombre: "Cereales Allbram",
        categoria: "cereales",
        medida_racion: 20,
        consumo_habitual: "Mediano (160g)",
        raciones_hc: 4,
        indice: 50
      },
      { nombre: "Cuscus_cocido",
        categoria: "cereales",
        medida_racion: 65,
        consumo_habitual: "Plato mediano (120g)",
        raciones_hc: 6,
        indice: 65
      },
      { nombre: "Fideos",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Peque�o\n(80g)",
        raciones_hc: 3,
        indice: 50
      },
      { nombre: "Galleta_tipo_Digestiva",
        categoria: "cereales",
        medida_racion: 16,
        consumo_habitual: "Unidad (11g)",
        raciones_hc: 0.7,
        indice: 65
      },
      { nombre: "Galleta_tipo_Maria",
        categoria: "cereales",
        medida_racion: 15,
        consumo_habitual: "Unidad (7g)",
        raciones_hc: 0.4,
        indice: 70
      },
      { nombre: "Galleta_tipo_Principe",
        categoria: "cereales",
        medida_racion: 14,
        consumo_habitual: "Unidad (15g)",
        raciones_hc: 1,
        indice: 70
      },
      {
        nombre: "Galleta_sin_azucar ",
        categoria: "cereales",
        medida_racion: 18,
        consumo_habitual: "Unidad (7g)",
        raciones_hc: 0.3,
        indice: 50
      },
      { nombre: "Garbanzo_cocido",
        categoria: "ereales",
        medida_racion: 50,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 6,
        indice: 35
      },
      { nombre: "Garbanzo_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Garbanzo_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Guarnici�n (100g)",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "Guisantes_lata",
        categoria: "cereales",
        medida_racion: 100,
        consumo_habitual: "Plato grande (600g)",
        raciones_hc: 6,
        indice: 35
      },
      { nombre: "Guisantes_lata",
        categoria: "cereales",
        medida_racion: 100,
        consumo_habitual: "Plato mediano (400g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Guisantes_lata",
        categoria: "cereales",
        medida_racion: 100,
        consumo_habitual: "Guarnici�n (200g)",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "Harina_trigo",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Cucharada sopera rasa (14g)",
        raciones_hc: 1,
        indice: 78
      },
      { nombre: "Harina_centeno",
        categoria: "Harina",
        medida_racion: 17,
        consumo_habitual: "Cucharada sopera rasa (14g)",
        raciones_hc: 0.8,
        indice: 45
      },
      { nombre: "Harina_soja",
        categoria: "Harina",
        medida_racion: 70,
        consumo_habitual: "Cucharada sopera rasa (14g)",
        raciones_hc: 0.2,
        indice: 25
      },
      { nombre: "Judias_blancas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 6,
        indice: 35
      },
      { nombre: "Judias_blancas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Judias_blancas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Guarnici�n (100g)",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "Lentejas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 6,
        indice: 35
      },
      { nombre: "Lentejas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Lentejas_cocido",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Guarnici�n (100g)",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "z_lata",
        categoria: "cereales",
        medida_racion: 50,
        consumo_habitual: "Lata peque�a (150g)",
        raciones_hc: 3,
        indice: 65
      },
      { nombre: "Maiz_sin_azucar",
        categoria: "cereales",
        medida_racion: 90,
        consumo_habitual: "(150g) 3 65 Ma�z en lata sin az�car a�adido 90 Lata peque�a (150g)",
        raciones_hc: 1.5,
        indice: 30
      },
      { nombre: "Mijo_cocido",
        categoria: "cereales",
        medida_racion: 53,
        consumo_habitual: "Guarnici�n (100g)",
        raciones_hc: 6,
        indice: 70
      },
      { nombre: "Múesli",
        categoria: "cereales",
        medida_racion: 15,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 65
      },
      { nombre: "Pan_blanco",
        categoria: "Harina",
        medida_racion: 20,
        consumo_habitual: "Barra de 1/4, unos 3 cm (20g)",
        raciones_hc: 1,
        indice: 70
      },
      { nombre: "Pan_blanco",
        categoria: "Harina",
        medida_racion: 20,
        consumo_habitual: "Barra de 1/4 entera (180g)",
        raciones_hc: 3,
        indice: 70
      },
      { nombre: "Pan_blanco",
        categoria: "Harina",
        medida_racion: 20,
        consumo_habitual: "Panecillo restaurante (60g)",
        raciones_hc: 9,
        indice: 70
      },
      { nombre: "Pan_molde",
        categoria: "Harina",
        medida_racion: 20,
        consumo_habitual: "Rebanada (25g)",
        raciones_hc: 1.2,
        indice: 85
      },
      { nombre: "Pan_hamburguesa",
        categoria: "Harina",
        medida_racion: 18,
        consumo_habitual: "Unidad\n(80g)",
        raciones_hc: 4.5,
        indice: 85
      },
      { nombre: "Pan_hamburguesa",
        categoria: "Harina",
        medida_racion: 18,
        consumo_habitual: "Unidad pequeña (55g)",
        raciones_hc: 3,
        indice: 85
      },
      { nombre: "Pan_integral",
        categoria: "Harina",
        medida_racion: 23,
        consumo_habitual: "Unidad\npequeña (55g)",
        raciones_hc: 2,
        indice: 40
      },
      { nombre: "Pan_rallado",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Cucharada sopera colmada (23g)",
        raciones_hc: 1.5,
        indice: 70
      },
      {
        nombre: "Pan tostado",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Unidad (10g)",
        raciones_hc: 0.6,
        indice: 70
      },
      { nombre: "Pan_tostado",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Unidad mini (3,3g)",
        raciones_hc: 0.25,
        indice: 70
      },
      { nombre: "Pan_tostado",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Tostada canap� (2g)",
        raciones_hc: 0.15,
        indice: 70
      },
      { nombre: "Pan_tostado",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "Krispoll (12,5g)",
        raciones_hc: 0.8,
        indice: 70
      },
      { nombre: "Pan_bastoncitos",
        categoria: "Harina",
        medida_racion: 15,
        consumo_habitual: "3 unidades (15g)",
        raciones_hc: 1,
        indice: 70
      },
      { nombre: "Pasta_cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 6,
        indice: 50
      },
      { nombre: "Pasta_cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 50
      },
      { nombre: "Pasta_cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Guarnici�n (100g)",
        raciones_hc: 2,
        indice: 50
      },
      {
        nombre: "Patata cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 6,
        indice: 65
      },
      {
        nombre: "Patata cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Plato mediano (200g)",
        raciones_hc: 4,
        indice: 65
      },
      { nombre: "Patata cocida",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Guarnicion (100g)",
        raciones_hc: 2,
        indice: 65
      },
      { nombre: "Patatas_fritas",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Guarnici�n (60g)",
        raciones_hc: 2,
        indice: 70
      },
      { nombre: "Patatas_fritas",
        categoria: "Harina",
        medida_racion: 50,
        consumo_habitual: "Porci�n hamburgueser�a\n(120g",
        raciones_hc: 4,
        indice: 70
      },
      { nombre: "Sushi",
        categoria: "Harina",
        medida_racion: 45,
        consumo_habitual: "Pieza\npeque�a\n(20g)",
        raciones_hc: 0.5,
        indice: 42
      },
      { nombre: "Sushi",
        categoria: "Harina",
        medida_racion: 45,
        consumo_habitual: "Pieza\ngrande\n(40g)",
        raciones_hc: 0.9,
        indice: 42
      },
      { nombre: "Aguacate",
        categoria: "Frutas",
        medida_racion: "Libre",
        consumo_habitual: "Guarnici�n (40g)",
        raciones_hc: 1.2,
        indice: 10
      },
      { nombre: "Albaricoque",
        categoria: " Frutas",
        medida_racion: "150",
        consumo_habitual: "Unidad mediana (50g)",
        raciones_hc: 0.3,
        indice: 30
      },
      { nombre: "Arandano",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.25,
        indice: 25
      },
      { nombre: "Castaña cruda",
        categoria: "Frutas",
        medida_racion: "30",
        consumo_habitual: "Unidad (10g)",
        raciones_hc: 0.3,
        indice: 65
      },
      {
        nombre: "Castaña tostada",
        categoria: "Frutas",
        medida_racion: "25",
        consumo_habitual: "Unidad (3g)",
        raciones_hc: 0.3,
        indice: 65
      },
      { nombre: "Cereza",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "12 unidades (100g)",
        raciones_hc: 1,
        indice: 25
      },
      { nombre: "Chirimoya",
        categoria: "Frutas",
        medida_racion: "50",
        consumo_habitual: "Unidad mediana (200g)",
        raciones_hc: 4,
        indice: 35
      },
      { nombre: "Ciruela",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "2 unidades (100g)",
        raciones_hc: 1,
        indice: 35
      },
      { nombre: "Coco_fresco",
        categoria: "Frutas",
        medida_racion: "200",
        consumo_habitual: "Tajada mediana (35g)",
        raciones_hc: 0.2,
        indice: 45
      },
      { nombre: "Coco_seco",
        categoria: "Frutas",
        medida_racion: "150",
        consumo_habitual: "Cucharada colmada (20g)",
        raciones_hc: 0.1,
        indice: 45
      },
      { nombre: "Frambuesa",
        categoria: "Frutas",
        medida_racion: "150",
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.2,
        indice: 25
      },
      { nombre: "Fresones",
        categoria: "Frutas",
        medida_racion: "200",
        consumo_habitual: "8 unidades grandes (200g)",
        raciones_hc: 1,
        indice: 25
      },
      { nombre: "Granada",
        categoria: "Frutas",
        medida_racion: "70",
        consumo_habitual: "Unidad mediana (175g)",
        raciones_hc: 2.5,
        indice: 35
      },
      { nombre: "Grosella",
        categoria: "Frutas",
        medida_racion: "200",
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.1,
        indice: 25
      },
      { nombre: "Grosella_negra",
        categoria: "Frutas",
        medida_racion: "140",
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.2,
        indice: 15
      },
      { nombre: "Higos",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (50g)",
        raciones_hc: 0.5,
        indice: 35
      },
      { nombre: "Kiwi",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (100g",
        raciones_hc: 1,
        indice: 50
      },
      { nombre: "Litchi",
        categoria: "Frutas",
        medida_racion: "70",
        consumo_habitual: "6 unidades (70g)",
        raciones_hc: 1,
        indice: 50
      },
      { nombre: "Mandarina",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (100g)",
        raciones_hc: 1,
        indice: 30
      },
      { nombre: "Mango",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (200g)",
        raciones_hc: 2,
        indice: 50
      },
      { nombre: "Manzana",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (200g)",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "Manzana_asada",
        categoria: "Frutas",
        medida_racion: "50",
        consumo_habitual: "Unidad mediana (120g)",
        raciones_hc: 2.5,
        indice: 35
      },
      { nombre: "Melocoton",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (200g)",
        raciones_hc: 2,
        indice: 35
      },
      {
        nombre: "Melocoton conserva",
        categoria: "Frutas",
        medida_racion: "50",
        consumo_habitual: "Una mitad (50g)",
        raciones_hc: 1,
        indice: 35
      },
      { nombre: "Melon",
        categoria: "Frutas",
        medida_racion: "200",
        consumo_habitual: "Un tajada mediana (200g)",
        raciones_hc: 1,
        indice: 60
      },
      { nombre: "Membrillo",
        categoria: "Frutas",
        medida_racion: "150",
        consumo_habitual: "Unidad mediana (350g)",
        raciones_hc: 2.5,
        indice: 35
      },
      { nombre: "Moras",
        categoria: "Frutas",
        medida_racion: "150",
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.15,
        indice: 25
      },
      { nombre: "Naranja",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana",
        raciones_hc: 2,
        indice: 35
      },
      { nombre: "Nectarina",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (100g)",
        raciones_hc: 1,
        indice: 35
      },
      { nombre: "Pera",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (200g)",
        raciones_hc: 2,
        indice: 30
      },
      { nombre: "Papaya",
        categoria: "Frutas",
        medida_racion: "125",
        consumo_habitual: "Una tajada (250g)",
        raciones_hc: 2,
        indice: 55
      },
      { nombre: "Paraguayo",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "Unidad mediana (100g)",
        raciones_hc: 1,
        indice: 35
      },
      { nombre: "Piña",
        categoria: "Frutas",
        medida_racion: "100",
        consumo_habitual: "2 rodajas (100g)",
        raciones_hc: 1,
        indice: 45
      },
      { nombre: "Piña jugo",
        categoria: "Frutas",
        medida_racion: "60",
        consumo_habitual: "2 rodajas (100g)",
        raciones_hc: 1.6,
        indice: 50
      },
      { nombre: "Platano",
        categoria: "Frutas",
        medida_racion: "50",
        consumo_habitual: "Unidad peque�a (100g)",
        raciones_hc: 2,
        indice: 50
      },
      { nombre: "Sandia",
        categoria: "Frutas",
        medida_racion: "200",
        consumo_habitual: "Una tajada grande (200g)",
        raciones_hc: 1,
        indice: 75
      },
      { nombre: "Uva",
        categoria: "Frutas",
        medida_racion: "50",
        consumo_habitual: "12 unidades (100g)",
        raciones_hc: 2,
        indice: 45
      },
      { nombre: "Acelga",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Plato grande (250g)",
        raciones_hc: 0.8,
        indice: 15
      },
      { nombre: "Ajo",
        categoria: "Hortalizas",
        medida_racion: 40,
        consumo_habitual: "3 dientes (10g)",
        raciones_hc: 0.25,
        indice: 30
      },
      { nombre: "Alcachofa",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Plato grande (150g)",
        raciones_hc: 0.5,
        indice: 20
      },
      { nombre: "Berenjena",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad grande (300g)",
        raciones_hc: 1,
        indice: 20
      },
      { nombre: "Berenjena",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Guarnici�n (125g)",
        raciones_hc: 0.4,
        indice: 20
      },
      { nombre: "Brócoli",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 1,
        indice: 15
      },
      { nombre: "Calabacín",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad grande (300g)",
        raciones_hc: 1,
        indice: 15
      },
      { nombre: "Calabaza",
        categoria: "Hortalizas",
        medida_racion: 200,
        consumo_habitual: "Plato grande (150g)",
        raciones_hc: 1,
        indice: 75
      },
      { nombre: "Cebolla",
        categoria: "Hortalizas",
        medida_racion: 150,
        consumo_habitual: "Unidad mediana (150g)",
        raciones_hc: 1,
        indice: 15
      },
      { nombre: "Coliflor",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Plato grande (300g)",
        raciones_hc: 1,
        indice: 15
      },
      { nombre: "Endibia",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad (100g)",
        raciones_hc: 0.3,
        indice: 15
      },
      { nombre: "Judia_verde",
        categoria: "Hortalizas",
        medida_racion: 250,
        consumo_habitual: "Plato grande (250g)",
        raciones_hc: 1,
        indice: 30
      },
      { nombre: "Lechuga",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Raci�n individual (70g)",
        raciones_hc: 0.25,
        indice: 15
      },
      { nombre: "Nabo",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad (100g)",
        raciones_hc: 0.3,
        indice: 30
      },
      { nombre: "Palmitos",
        categoria: "Hortalizas",
        medida_racion: 200,
        consumo_habitual: "Unidad (25g)",
        raciones_hc: 0.1,
        indice: 20
      },
      { nombre: "Pepino",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad mediana (150g)",
        raciones_hc: 0.5,
        indice: 15
      },
      { nombre: "Pimiento",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad mediana (150g)",
        raciones_hc: 0.5,
        indice: 15
      },
      { nombre: "Puerro",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad mediana (75g)",
        raciones_hc: 0.25,
        indice: 15
      },
      { nombre: "Rábano",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "5 unidades medianas (100g)",
        raciones_hc: 0.3,
        indice: 15
      },
      { nombre: "Remolacha",
        categoria: "Hortalizas",
        medida_racion: 150,
        consumo_habitual: "unidad mediana (100g",
        raciones_hc: 2,
        indice: 30
      },
      { nombre: "Repollo",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Guarnici�n (125g)",
        raciones_hc: 0.4,
        indice: 15
      },
      { nombre: "Setas",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Plato grande (200g)",
        raciones_hc: 0.7,
        indice: 15
      },
      { nombre: "Tomate",
        categoria: "Hortalizas",
        medida_racion: 300,
        consumo_habitual: "Unidad mediana (150g)",
        raciones_hc: 0.5,
        indice: 30
      },
      { nombre: "Zanahoria",
        categoria: "Hortalizas",
        medida_racion: 150,
        consumo_habitual: "Unidad mediana (70g)",
        raciones_hc: 0.3,
        indice: 30
      },
      { nombre: "Zanahoria_hervida",
        categoria: "Hortalizas",
        medida_racion: 200,
        consumo_habitual: "Unidad mediana (70g)",
        raciones_hc: 0.5,
        indice: 85
      },
      { nombre: "Fruta_seca",
        categoria: "Aceituna Fruta_seca",
        medida_racion: 250,
        consumo_habitual: "Una tapa (12 unidad. o 30g)",
        raciones_hc: 0,
        indice: 15
      },
      { nombre: "",
        categoria: "Albaricoque seco Fruta_seca",
        medida_racion: 15,
        consumo_habitual: "Unidad (5g)",
        raciones_hc: 0.3,
        indice: 35
      },
      { nombre: "Almendra",
        categoria: "Fruta_seca",
        medida_racion: 150,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.1,
        indice: 15
      },
      { nombre: "Almendra_seca",
        categoria: "Fruta_seca",
        medida_racion: 140,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.1,
        indice: 15
      },
      { nombre: "Avellana",
        categoria: "Fruta_seca",
        medida_racion: 150,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.1,
        indice: 15
      },
      { nombre: "Cacahuete",
        categoria: "Fruta_seca",
        medida_racion: 100,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.2,
        indice: 15
      },
      { nombre: "Ciruela_pasa",
        categoria: "Fruta_seca",
        medida_racion: 15,
        consumo_habitual: "Unidad (8g)",
        raciones_hc: 0.5,
        indice: 40
      },
      { nombre: "Dátil_seco",
        categoria: "Fruta_seca",
        medida_racion: 15,
        consumo_habitual: "Unidad (10g)",
        raciones_hc: 0.7,
        indice: 70
      },
      { nombre: "Higo_seco",
        categoria: "Fruta_seca",
        medida_racion: 15,
        consumo_habitual: "Unidad (8g)",
        raciones_hc: 0.5,
        indice: 40
      },
      { nombre: "Nuez",
        categoria: "Fruta_seca",
        medida_racion: 300,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0,
        indice: 15
      },
      { nombre: "Piñon",
        categoria: "Fruta_seca",
        medida_racion: 300,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0,
        indice: 15
      },
      { nombre: "Pipas",
        categoria: "Fruta_seca",
        medida_racion: 80,
        consumo_habitual: "Pu�ado, con mano cerrada (15g)",
        raciones_hc: 0.2,
        indice: 35
      },
      { nombre: "Pistacho",
        categoria: "Fruta_seca",
        medida_racion: 80,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 0.2,
        indice: 15
      },
      { nombre: "Sésamo",
        categoria: "Fruta_seca",
        medida_racion: 100,
        consumo_habitual: "Cucharada sopera rasa (12g)",
        raciones_hc: 0.1,
        indice: 35
      },
      { nombre: "Uva_pasa",
        categoria: "Fruta_seca",
        medida_racion: 15,
        consumo_habitual: "Pu�ado, con mano cerrada (20g)",
        raciones_hc: 1.25,
        indice: 65
      },
      {
        nombre: "Bebida isotónica",
        categoria: "Bebidas",
        medida_racion: 130,
        consumo_habitual: "Lata de\n330cc",
        raciones_hc: 2.5,
        indice: 78
      },
      {
        nombre: "Bebida isotónica",
        categoria: "Bebidas",
        medida_racion: 130,
        consumo_habitual: "Botella de 500cc",
        raciones_hc: 3.8,
        indice: 78
      },
      { nombre: "Bebida_refrescante",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Vaso de 200cc",
        raciones_hc: 2,
        indice: 70
      },
      { nombre: "Bebida_refrescante",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Lata de 330cc",
        raciones_hc: 3.3,
        indice: 70
      },
      { nombre: "Bebida_cacao",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Vaso o brick de 200cc",
        raciones_hc: 2,
        indice: 34
      },
      { nombre: "Bebida_soja",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Vaso o brick de 200cc",
        raciones_hc: 0.8,
        indice: 30
      },
      { nombre: "Bebida_energetica",
        categoria: "Bebidas",
        medida_racion: 80,
        consumo_habitual: "Lata de 250cc",
        raciones_hc: 3,
        indice: 70
      },
      { nombre: "Bitter",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Vaso o botell�n de 200cc",
        raciones_hc: 2,
        indice: 70
      },
      { nombre: "Cerveza",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Vaso o ca�a de (200cc)",
        raciones_hc: 0.8,
        indice: 110
      },
      { nombre: "Cerveza",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Tercio o mediana (330cc)",
        raciones_hc: 1.3,
        indice: 110
      },
      { nombre: "Cerveza",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Jarra (500cc)",
        raciones_hc: 2,
        indice: 110
      },
      { nombre: "Cerveza_sin_alcohol",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Vaso o ca�a de (200cc)",
        raciones_hc: 0.8,
        indice: 110
      },
      { nombre: "Cerveza_sin_alcohol",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Tercio o mediana (330cc)",
        raciones_hc: 1.3,
        indice: 110
      },
      { nombre: "Cerveza_sin_alcohol",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Jarra (500cc)",
        raciones_hc: 2,
        indice: 110
      },
      { nombre: "Tónica",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Un vaso o botell�n (200cc)",
        raciones_hc: 2,
        indice: 70
      },
      { nombre: "Zumo_fruta_comercial",
        categoria: "Bebidas",
        medida_racion: 100,
        consumo_habitual: "Un vaso o brick (200cc)",
        raciones_hc: 2,
        indice: 60
      },
      { nombre: "Zumo_fruta",
        categoria: "Bebidas",
        medida_racion: 250,
        consumo_habitual: "Un vaso o brick (200cc)",
        raciones_hc: 0.8,
        indice: 45
      },
      { nombre: "Azúcar blanco",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Cucharada postre (8g)",
        raciones_hc: 0.8,
        indice: 70
      },
      { nombre: "car_blanco",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Cucharada sopera (20g)",
        raciones_hc: 2,
        indice: 70
      },
      {
        nombre: "Azúcar blanco",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Sobre (8g) Otros",
        raciones_hc: 0.8,
        indice: 70
      },
      {
        nombre: "Azúcar moreno",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Cucharada postre (8g)",
        raciones_hc: 0.8,
        indice: 70
      },
      {
        nombre: "Azúcar moreno",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Cucharada sopera (20g)",
        raciones_hc: 2,
        indice: 70
      },
      {
        nombre: "Azúcar moreno",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Sobre (8g)",
        raciones_hc: 0.8,
        indice: 70
      },
      {
        nombre: "Barrita energética",
        categoria: "Otros",
        medida_racion: 20,
        consumo_habitual: "Unidad (25g)",
        raciones_hc: 1.25,
        indice: 70
      },
      { nombre: "Bizcocho",
        categoria: "Otros",
        medida_racion: 20,
        consumo_habitual: "Unidad comercial individual (25g)",
        raciones_hc: 1.25,
        indice: 65
      },
      {
        nombre: "Cruasán",
        categoria: "Otros",
        medida_racion: 20,
        consumo_habitual: "Unidad (60g)",
        raciones_hc: 3,
        indice: 70
      },
      { nombre: "Cacao_polvo",
        categoria: "Otros",
        medida_racion: 12,
        consumo_habitual: "Cucharada postre (8g)",
        raciones_hc: 0.7,
        indice: 25
      },
      { nombre: "Cacao_polvo",
        categoria: "Otros",
        medida_racion: 12,
        consumo_habitual: "Cucharada sopera (20g)",
        raciones_hc: 1.7,
        indice: 25
      },
      { nombre: "Caramelo",
        categoria: "Otros",
        medida_racion: 12,
        consumo_habitual: "Unidad (5g)",
        raciones_hc: 0.4,
        indice: 70
      },
      { nombre: "Chocolate_blanco",
        categoria: "Otros",
        medida_racion: 17,
        consumo_habitual: "Pastilla (8g)",
        raciones_hc: 0.5,
        indice: 70
      },
      { nombre: "Chocolate_blanco",
        categoria: "Otros",
        medida_racion: 17,
        consumo_habitual: "Tableta individual (30g)",
        raciones_hc: 1.7,
        indice: 70
      },
      { nombre: "Chocolate_negro",
        categoria: "Otros",
        medida_racion: 25,
        consumo_habitual: "Pastilla (8g)",
        raciones_hc: 0.3,
        indice: 25
      },
      { nombre: "Chocolate_negro",
        categoria: "Otros",
        medida_racion: 25,
        consumo_habitual: "Tableta individual (30g)",
        raciones_hc: 1.2,
        indice: 25
      },
      { nombre: "Crema_cacao",
        categoria: "Otros",
        medida_racion: 25,
        consumo_habitual: "Cucharada sopera colmada (25g)",
        raciones_hc: 1,
        indice: 55
      },
      { nombre: "Crema_cacahuete",
        categoria: "Otros",
        medida_racion: 100,
        consumo_habitual: "Cucharada sopera colmada (20g)",
        raciones_hc: 0.2,
        indice: 40
      },
      { nombre: "Donut",
        categoria: "Otros",
        medida_racion: 23,
        consumo_habitual: "Unidad (58g)",
        raciones_hc: 2.5,
        indice: 75
      },
      {
        nombre: "Fructosa",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Cucharada sopera (20g)",
        raciones_hc: 2,
        indice: 20
      },
      { nombre: "Glucosa",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Pastilla peque�a (2,5g)",
        raciones_hc: 0.25,
        indice: 100
      },
      { nombre: "Glucosa",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Pastilla normal (5g)",
        raciones_hc: 0.5,
        indice: 100
      },
      { nombre: "Glucosa",
        categoria: "Otros",
        medida_racion: 10,
        consumo_habitual: "Gel deport (40g)",
        raciones_hc: 2.5,
        indice: 100
      },
      { nombre: "Golosinas",
        categoria: "Otros",
        medida_racion: 18,
        consumo_habitual: "Unidad (60g)",
        raciones_hc: 3,
        indice: 70
      },
      { nombre: "Ketchup",
        categoria: "Otros",
        medida_racion: 50,
        consumo_habitual: "Unidad",
        raciones_hc: 0.2,
        indice: 55
      },
      { nombre: "Mermelada",
        categoria: "Otros",
        medida_racion: 20,
        consumo_habitual: "Cucharada sopera (25g)",
        raciones_hc: 1.25,
        indice: 65
      },
      { nombre: "Mermelada_light",
        categoria: "Otros",
        medida_racion: 50,
        consumo_habitual: "Unidad (90g)",
        raciones_hc: 1.5,
        indice: 35
      },
      { nombre: "Miel",
        categoria: "Otros",
        medida_racion: 13,
        consumo_habitual: "Cucharada sopera (18g)",
        raciones_hc: 1.3,
        indice: 85
      },
      { nombre: "Palomitas",
        categoria: "Otros",
        medida_racion: 15,
        consumo_habitual: "Unidad (150g)",
        raciones_hc: 2.5,
        indice: 85
      },
      { nombre: "Pizza",
        categoria: "Otros",
        medida_racion: 40,
        consumo_habitual: "Tri�ngulo (100g o 1/4 parte de pizza)",
        raciones_hc: 2.5,
        indice: 45
      },
      { nombre: "Pizza",
        categoria: "Otros",
        medida_racion: 40,
        consumo_habitual: "Media pizza (200g)",
        raciones_hc: 5,
        indice: 45
      },
      { nombre: "Pizza",
        categoria: "Otros",
        medida_racion: 40,
        consumo_habitual: "Pizza individual (400g)",
        raciones_hc: 10,
        indice: 45
      }
    ]
})

/* ------------- Reducers ------------- */

// failed to get the avatar
export const addSugarLevel = (state, { sugarLevel }) => {
   return state.merge({ events: [...state.events, sugarLevel] })
}

export const addCalculatedInsuline = (state, { calculatedInsuline }) => {
  console.tron.log(12121);
  console.tron.log(calculatedInsuline);
  return state.merge({ calculatedInsuline: calculatedInsuline })
}
/* ------------- Hookup Reducers To Types ------------- */

export const reducer = createReducer(INITIAL_STATE, {
   [Types.ADD_SUGAR_LEVEL]: addSugarLevel,
   [Types.ADD_CALCULATED_INSULINE]: addCalculatedInsuline
})
